### ISSUE TITLE
Can't build with MacPorts due to OpenSSL problem

### ISSUE THREAD

**Issue by simsong** [blackbagtech/sleuthkit-APFS#4]
I'm trying to build this on a clean install of MacOS 10.14.2 with MacPorts. I'm having problems with OpenSSL support:

```
checking for openssl/ssl.h in /usr/local/ssl... no
checking for openssl/ssl.h in /usr/lib/ssl... no
checking for openssl/ssl.h in /usr/ssl... no
checking for openssl/ssl.h in /usr/pkg... no
checking for openssl/ssl.h in /usr/local... no
checking for openssl/ssl.h in /usr... no
checking whether compiling and linking against OpenSSL works... no
configure: error: OpenSSL headers cannot be located. Consider using the --with-openssl option to specify an appropriate path.
```

The thing is, I have OpenSSL installed:

```
[nimi ~/gits/sleuthkit-APFS 22:33:27](develop-APFS) $ ls -l /opt/local/include/openssl/ssl.h
-rw-r--r--  1 root  admin  149159 Nov 22 17:21 /opt/local/include/openssl/ssl.h
[nimi ~/gits/sleuthkit-APFS 22:34:55](develop-APFS) $ 

```

I am also able to compile the ssl test program:

```
[nimi ~/gits/sleuthkit-APFS 22:34:55](develop-APFS) $ cat x.cpp
#include <openssl/ssl.h>
int
main ()
{
  SSL_new(NULL);
  return 0;
}
[nimi ~/gits/sleuthkit-APFS 22:35:16](develop-APFS) $ gcc x.cpp -I/opt/local/include/ -L/opt/local/lib/ -lssl
[nimi ~/gits/sleuthkit-APFS 22:35:23](develop-APFS) $ 

```

However, when I specify those CFLAGS and LD_FLAGS for configure, I get the same error.

**Comment by jtsylve** [comment]
I'm using the [ax_check_openssl](https://github.com/blackbagtech/sleuthkit-APFS/blob/develop-APFS/m4/ax_check_openssl.m4) macro from autoconf-archive for detection.  It doesn't seem to check all of the possible locations for openssl on macOS.  I don't use MacPorts, so I'm not totally clear on where they install openssl too, but for openssl installed via homebrew, I configure using something like the following to make the detection work:

```./configure --with-openssl=/usr/local/opt/openssl```

This doesn't seem to be needed on Linux systems.  Hopefully, there's a similar path you can provide to point it to the MacPorts version.  Please let me know if this works and if there are any suggestions to make the auto-detection work better on macOS.

**Comment by simsong** [comment]
I tried that and it didn’t work. I’ll try changing the macro to what I used with bulk_extractor and see how that goes. Thanks!


----
Sent from my phone.

On Dec 31, 2018, at 1:19 PM, Joe Sylve <notifications@github.com> wrote:

I'm using the ax_check_openssl macro from autoconf-archive for detection. It doesn't seem to check all of the possible locations for openssl on macOS. I don't use MacPorts, so I'm not totally clear on where they install openssl too, but for openssl installed via homebrew, I configure using something like the following to make the detection work:

./configure --with-openssl=/usr/local/opt/openssl

This doesn't seem to be needed on Linux systems. Hopefully, there's a similar path you can provide to point it to the MacPorts version. Please let me know if this works and if there are any suggestions to make the auto-detection work better on macOS.

**Comment by simsong** [comment]
Here is the openssl detection code from tcpflow:

```
################################################################                                                                              
## OpenSSL Support (required for AFFLIB and hash_t )                                                                                          
AC_CHECK_HEADERS([openssl/aes.h openssl/bio.h openssl/evp.h openssl/hmac.h openssl/md5.h openssl/pem.h openssl/rand.h openssl/rsa.h openssl/s\
ha.h openssl/pem.h openssl/x509.h])
AC_CHECK_LIB([dl],[dlopen])                   dnl apparently OpenSSL now needs -ldl on some Linux                                             
AC_CHECK_LIB([crypto],[EVP_get_digestbyname])   # if crypto is available, get it                                                              
AC_CHECK_LIB([md],[MD5])                        # if libmd is available, get it                                                               

# Need either SSL_library_init or OPENSSL_init_ssl, depending on openssl version                                                              
AC_CHECK_LIB([ssl],[SSL_library_init],,
     AC_CHECK_LIB([ssl],[OPENSSL_init_ssl],,
          AC_MSG_ERROR([OpenSSL developer library 'libssl-dev' or 'openssl-devel' not installed])))

AC_CHECK_FUNCS([MD5_Init EVP_get_digestbyname])


```

**Comment by simsong** [comment]
Changing out the existing OpenSSL detection for mine, and then using this, it works:

    $ CPPFLAGS=-I/opt/local/include LDFLAGS=-L/opt/local/lib ./configure

**Comment by jtsylve** [comment]
Does adding `/opt/local` to the list of paths [here](https://github.com/blackbagtech/sleuthkit-APFS/blob/develop-APFS/m4/ax_check_openssl.m4#L70) help?

**Comment by simsong** [comment]
Wow, what an incredibly gross script. Didn't RMS teach them not to put hard coded constants in the middle of a script like that? 

Yes, that solves the problem!  Put it first. Can you make the change?

**Comment by jtsylve** [comment]
Will do.  I might as well make it auto-detect the homebrew path while I'm at it.  Thanks for the help.

**Comment by simsong** [comment]
Some compile warnings:

```
hfs.c:834:60: warning: format specifies type 'unsigned short' but the argument has type 'unsigned long' [-Wformat]
                        PRIu16 ")", rec, cur_node, keylen, (nodesize - rec_off));
~~~~~~~~~~~~~~~~~~~~~~~~                                   ^~~~~~~~~~~~~~~~~~~~
hfs.c:830:28: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (keylen >= nodesize - rec_off) {
                    ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~
```
and:

```
yaffs.cpp:89:90: warning: format specifies type 'unsigned long long' but the argument has type 'uint32_t' (aka 'unsigned int') [-Wformat]
                "yaffsfs_parse_image_load_cache: Max object ID %" PRIuOFF " is invalid", obj_id);
                                                               ~~~                       ^~~~~~
yaffs.cpp:97:95: warning: format specifies type 'unsigned long long' but the argument has type 'uint32_t' (aka 'unsigned int') [-Wformat]
                "yaffsfs_parse_image_load_cache: Max version number %" PRIuOFF " is invalid", version_num);
```


```
binsrch_index.cpp:1154:24: warning: data argument not used by format string [-Wformat-extra-args]
            func_name, hdb_binsrch_info->hash_len, strlen(hash));
                       ^
```

**Comment by simsong** [comment]
Thanks. I'll think about it. homebrew is definitely Linux comes to MacOS. MacPorts is BSD, and MacOS is BSD, so it should work better. Sometimes it does, sometimes it doesn't. It seems to handle upgrading quite well.
